[package]
name = "rust-actix"
version = "0.1.0"
edition = "2021"

# app/main.rs をバイナリとして使う
[[bin]]
name = "main"
path = "app/main.rs"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

