[package]
name = "hello-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }

# バイナリのエントリポイントを app/main.rs に変更
[[bin]]
name = "main"
path = "app/main.rs"
